ext {
    extName = 'Anitummy'
    extClass = '.Anitusk'
    extVersionCode = 23
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:unpacker"))
    implementation(project(":lib:vidhide-extractor"))
    implementation(project(":lib:dood-extractor"))
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:cloudflare-interceptor"))
    implementation(project(":lib:m3u8server"))
}

