ext {
    extName = 'Gogoanime'
    extClass = '.Gogoanime'
    extVersionCode = 5
    isNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:byse-extractor"))
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:universal-extractor"))
    implementation(project(":lib:vidmoly-extractor"))
}
