ext {
    extName = 'ZoroTv'
    extClass = '.ZoroTv'
    extVersionCode = 30
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:blogger-extractor"))
    implementation(project(":lib:universal-extractor"))
    implementation(project(":lib:unpacker"))
}
