ext {
    extName = 'ReAnime'
    extClass = '.ReAnime'
    extVersionCode = 32
    isNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(':lib:playlist-utils'))
    implementation(project(':lib:cloudflare-interceptor'))
    implementation(project(':lib:m3u8server'))
    implementation("com.github.NanoHttpd.nanohttpd:nanohttpd:-SNAPSHOT")
}
