ext {
    extName = 'ReAnime'
    extClass = '.ReAnime'
    extVersionCode = 23
    isNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(':lib:playlist-utils'))
    implementation(project(':lib:cloudflare-interceptor'))
    implementation(project(':lib:m3u8server'))
    implementation("com.github.NanoHttpd.nanohttpd:nanohttpd:nanohttpd-project-2.3.1")
}
