ext {
    extName = 'WatchAnimeWorld'
    extClass = '.WatchAnimeWorld'
    extVersionCode = 27
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(':lib:abyss-extractor'))
    implementation(project(':lib:cloudflare-interceptor'))
    implementation(project(':lib:playlist-utils'))
}
