ext {
    extName = 'AniSnatch'
    extClass = '.AniSnatch'
    extVersionCode = 23
}

apply from: "$rootDir/common.gradle"

android {
    defaultConfig {
        manifestPlaceholders.appName = "AniSnatch"
    }
}

dependencies {
    implementation(project(":lib:streamwish-extractor"))
    implementation(project(":lib:m3u8server"))
    implementation(project(":lib:unpacker"))
}
