ext {
    extName = 'AniSnatch'
    extClass = '.AniSnatch'
    extVersionCode = 11
}

apply from: "$rootDir/common.gradle"

android {
    defaultConfig {
        manifestPlaceholders.appName = "AniSnatch"
    }
}

dependencies {
    implementation(project(":lib:streamwish-extractor"))
    implementation(project(":lib:m3u8server"))
    implementation(libs.jsunpacker) {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
}
