ext {
    extName = 'Oneshows'
    extClass = '.Oneshows'
    extVersionCode = 8
    isNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:dood-extractor"))
    implementation(project(":lib:filemoon-extractor"))
    implementation(project(":lib:streamtape-extractor"))
    implementation(project(":lib:universal-extractor"))
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:m3u8server"))
}
