ext {
    extName = 'AniWave'
    extClass = '.AniWave'
    themePkg = 'anikototheme'
    overrideVersionCode = 4
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:playlist-utils"))
}

android {
    defaultConfig {
        manifestPlaceholders.appName = "AniWave"
    }
}
