ext {
    extName = 'Toonhub4u'
    extClass = '.Toonhub4u'
    extVersionCode = 2
}

apply from: "$rootDir/common.gradle"

android {
    defaultConfig {
        manifestPlaceholders.appName = "Toonhub4u"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    kotlin {
        jvmToolchain(17)
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

}

dependencies {
    implementation(project(':lib:filemoon-extractor'))
    implementation(project(':lib:streamwish-extractor'))
    implementation(project(':lib:vidhide-extractor'))
    implementation(project(':lib:buzzheavier-extractor'))
}


