ext {
    extName = "Flixer"
    extClass = ".Flixer"
    extVersionCode = 6
    isNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:unpacker"))
    implementation(project(":lib:vidsrc-extractor"))
    implementation(project(":lib:playlist-utils"))
}
