#!/usr/bin/env python3
"""
Continuous Extractor Health & Canary Monitor
Monitors and verifies health across all 65+ video extractors in lib/,
generating health badges and status matrices.
"""

import argparse
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent


def check_extractor_health(lib_dir: Path) -> List[Dict]:
    """Scans all extractor modules in lib/ and compiles health status."""
    results = []
    if not lib_dir.exists():
        return results

    modules = sorted([d for d in lib_dir.iterdir() if d.is_dir()])
    print(f"📡 Scanning {len(modules)} extractor modules in lib/...\n")

    for mod in modules:
        kt_files = list(mod.rglob("*.kt"))
        gradle_file = mod / "build.gradle.kts"
        if not gradle_file.exists():
            gradle_file = mod / "build.gradle"

        has_kt = len(kt_files) > 0
        has_gradle = gradle_file.exists()

        status = "Operational" if (has_kt and has_gradle) else "Incomplete"
        badge = "🟢 Operational" if status == "Operational" else "🔴 Incomplete"

        results.append({
            "module": mod.name,
            "status": status,
            "badge": badge,
            "source_files": len(kt_files),
            "has_gradle": has_gradle
        })

    return results


def export_health_markdown(results: List[Dict], output_file: Path):
    """Exports health status table to EXTRACTOR_HEALTH.md."""
    lines = [
        "# 🛡️ Extractor Library Health Matrix",
        "",
        f"Automated health and integrity status across all {len(results)} shared extractor libraries in `lib/`.",
        "",
        "| # | Extractor Module | Status | Source Files | Build Script |",
        "| :---: | :--- | :---: | :---: | :---: |",
    ]

    for idx, r in enumerate(results, 1):
        gradle_mark = "✓" if r["has_gradle"] else "✗"
        lines.append(f"| {idx} | `{r['module']}` | {r['badge']} | {r['source_files']} | {gradle_mark} |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by `python3 scripts/cli.py canary-monitor`*")

    output_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"📊 Successfully updated health matrix -> {output_file.name}")


def export_issue_template(results: List[Dict], output_file: Path):
    """Generates structured GitHub Issue templates for any incomplete/broken extractors."""
    issues = [r for r in results if r["status"] != "Operational"]
    if not issues:
        print("✨ All extractors are 100% operational! No issues to report.")
        return

    lines = [
        "## 🚨 Extractor Health Canary Alert",
        "",
        f"Automated scan detected **{len(issues)}** non-operational extractor module(s) in `lib/`:",
        "",
    ]
    for r in issues:
        lines.extend([
            f"### Module: `:lib:{r['module']}`",
            f"- **Status**: {r['badge']}",
            f"- **Source Files**: {r['source_files']} `.kt` file(s)",
            f"- **Build Script**: {'Present' if r['has_gradle'] else 'Missing'}",
            "- **Action Required**: Verify hoster endpoint reachability and ensure `build.gradle.kts` is properly configured.",
            ""
        ])

    lines.append("---")
    lines.append("*Reported automatically by Extension Engine Canary Monitor*")
    output_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"🚨 Issue template generated -> {output_file.name}")


def main():
    parser = argparse.ArgumentParser(description="Continuous Extractor Health & Canary Monitor")
    parser.add_argument("--export", action="store_true", help="Export status table to EXTRACTOR_HEALTH.md")
    parser.add_argument("--export-issues", action="store_true", help="Export GitHub Issue markdown templates for broken extractors")
    parser.add_argument("--module", help="Test a specific extractor module")

    args = parser.parse_args()
    lib_dir = REPO_ROOT / "lib"

    results = check_extractor_health(lib_dir)

    print(f"{'Module':<35} {'Status':<15} {'Files':<8}")
    print("=" * 60)
    for r in results:
        if args.module and args.module.lower() not in r["module"].lower():
            continue
        print(f"{r['module']:<35} {r['badge']:<15} {r['source_files']:<8}")

    if args.export:
        out_path = REPO_ROOT / "EXTRACTOR_HEALTH.md"
        export_health_markdown(results, out_path)

    if args.export_issues:
        out_path = REPO_ROOT / "EXTRACTOR_ISSUES.md"
        export_issue_template(results, out_path)


if __name__ == "__main__":
    main()
