ext {
    extName = 'Vidbox'
    extClass = '.Vidbox'
    extVersionCode = 2
    isNsfw = false
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:vidsrc-extractor"))
    implementation(project(":lib:universal-extractor"))
}
