name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete_merged_branch:
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 5
    if: github.event.pull_request.merged == true && github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.2.2

      - name: Delete branch
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$BRANCH_NAME" != "main" ] && [ "$BRANCH_NAME" != "master" ]; then
            echo "Deleting branch $BRANCH_NAME"
            git push origin --delete "$BRANCH_NAME"
          else
            echo "Skipping deletion of main or master branch"
          fi
